services:
  database:
    image: mysql:lts
    container_name: assistantships-db-hw-3-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: assistantships_db
